;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2026 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 14-0000-FFFF-88                      |
; |                        auth <admin@hex-rays.com>                        |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : EFDADABF30322E6DD8C88461D3E0C1D0B520AC4CE9162AE05F173B00296B9659
; Input MD5    : 44CAC57F7B1A0B26270099CA894568C2
; Input CRC32  : ECE21EC7
; Compiler     : Visual C++ (guessed)


                .686p
                .mmx
                .model flat

; ===========================================================================

; Segment type: Pure code
HEADER          segment page public 'DATA' use32
                assume cs:HEADER
                assume es:nothing, ss:nothing, ds:HEADER, fs:nothing, gs:nothing
                public __ImageBase
__ImageBase     db ?
HEADER          ends


                end __ImageBase
